### ISSUE TITLE
作者您好，为什么我启动报错？

### ISSUE THREAD

**Issue by happy-to-code** [qq53182347/liugh-parent#36]
![image](https://user-images.githubusercontent.com/57335544/78417873-302b2900-7669-11ea-9ec5-d3f0a98f664b.png)
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at com.liugh.SpringbootApplication.main(SpringbootApplication.java:21)
Caused by: java.lang.NullPointerException: null
	at com.liugh.config.MyCommandLineRunner.doScanner(MyCommandLineRunner.java:165)
	at com.liugh.config.MyCommandLineRunner.run(MyCommandLineRunner.java:39)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:792)
	... 5 common frames omitted

**Comment by happy-to-code** [comment]
找到原因了  我的文件路径有特殊字符
